# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(308, 53)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_layout = QtWidgets.QHBoxLayout()
        self.left_layout.setObjectName("left_layout")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.left_layout.addWidget(self.lineEdit)
        self.horizontalLayout_4.addLayout(self.left_layout)
        self.right_layout = QtWidgets.QHBoxLayout()
        self.right_layout.setObjectName("right_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.right_layout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.right_layout.addLayout(self.horizontalLayout_2)
        self.right_layout.setStretch(0, 1)
        self.right_layout.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.right_layout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
